name: CI

on:
  pull_request:
    branches:
      - fullstack-py-ts-rewrite

jobs:
  server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - run: uv sync --frozen

      - run: uv run ruff check .
      - run: uv run mypy app
      - run: uv run pytest
